# Server configuration
server:
  port: 8082
  tomcat:
    max-swallow-size: -1
    connection-timeout: 300000

# Multipart configuration
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 500MB
      file-size-threshold: 10MB
      location: ./temp
      resolve-lazily: false

  # HTTP configuration
  http:
    multipart:
      enabled: true

  # Database configuration
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

  h2:
    console:
      enabled: true

# Logging
logging:
  level:
    com.example.docprocessor: DEBUG
    org.springframework.web.multipart: DEBUG
    org.springframework.web: DEBUG
    org.apache.commons.fileupload: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG